# Theme App Extension Configuration
api_version = "2023-10"

[[extensions]]

uid = "a2274091-89f7-01b4-1067-13d60045030b40d0fae7"

type = "theme_app_extension"
name = "Bidly Auction Widget"
handle = "bidly-auction-widget"

[extensions.settings]
[[extensions.settings.blocks]]
type = "auction_list"
name = "Auction List"
limit = 1

[[extensions.settings.blocks]]
type = "auction_single"
name = "Single Auction"
limit = 5

[[extensions.settings.blocks]]
type = "auction_featured"
name = "Featured Auction"
limit = 1

[[extensions.settings.blocks]]
type = "auction_product_widget"
name = "Auction Product Widget"
limit = 1
